##############################################################################
#																			 #
#	Makefile for MacOS X interface											 #
#																			 #
#	created 17 August 1992													 #
#																			 #
##############################################################################



# include configuration and all makefile macro definitions
include ../../ug.conf

OBJECTS = MGraphicWindow.o MInterface.o MGraphicView.o


# local C compiler flags
LCFLAGS = -I../../include -Wall -fno-common -pipe

all : $(OBJECTS) $(GUI) Makefile.mif
	$(ARCH_AR)  $(ARCH_ARFLAGS) ../../lib/libdevM.a $(OBJECTS) 

.m.o: *.h *.m
	$(ARCH_CC) $(UG_CFLAGS) $(LCFLAGS) -ObjC $<

ON:
	echo "creating gui toolbox"
	cd gui; make -f Makefile.gui; cd ..;

OFF:
	echo "no gui toolbox"

clean:
	find . -name '*.o' -exec rm -f {} \; -print
	find . -name '*.a' -exec rm -f {} \; -print

extract:
	$(ARCH_AR) $(ARCH_EXFLAGS) ../../lib/libdevX.a $(OBJECTS)

xmc: extract all clean
