##############################################################################
#																			 #
#	Makefile for all modules of ug version 3								 #
#																			 #
#	created 16 December 1994												 #
#																			 #
##############################################################################

# load architecture dependent makefile	
include ../ug.arch
include ../ug.conf

# architecture-dependent makefile entries
include ../machines/mk.$(ARCHDIR)

LCFLAGS = -I../low -I../dddif

# select your devices: one of XIF or SIF, META is optional
DEVICES = XIF META
OBJECTS = devices.o

all : $(OBJECTS) $(DEVICES) Makefile.dev
	ar $(ARFLAGS) ../lib/libdev.a $(OBJECTS)

.c.o:
	$(CC) $(UGDEFINES) $(CFLAGS) $(LCFLAGS) $<

XIF:
	cd xif; make -f Makefile.xif; cd ..;

SIF:
	cd sif; make -f Makefile.sif; cd ..;

META:
	cd meta; make -f Makefile.meta; cd ..;

XLIB: 
	rm -f ../lib/libdev.a
	ar $(ARFLAGS) ../lib/libdev.a $(OBJECTS)
	cd meta; make -f Makefile.meta; cd ..;
	cd xif; make -f Makefile.xif; cd ..;

SLIB: 
	rm -f ../lib/libdev.a
	ar $(ARFLAGS) ../lib/libdev.a $(OBJECTS)
	cd meta; make -f Makefile.meta; cd ..;
	cd sif; make -f Makefile.sif; cd ..;

clean:
	rm $(OBJECTS)
	cd xif;  make -f Makefile.xif  clean; cd ..;
	cd sif;  make -f Makefile.sif  clean; cd ..;
	cd meta; make -f Makefile.meta clean; cd ..;

