##############################################################################
#																			 #
#	Makefile for all modules of ug version 3								 #
#																			 #
#	created 16 December 1994												 #
#																			 #
##############################################################################

# load architecture dependent makefile	
include ../ug.arch

# architecture-dependent makefile entries
include ../machines/mk.$(ARCHDIR)

LCFLAGS = -I../low

# the following list may be extended
DEVICES = XIF META
OBJECTS = devices.o

all : $(OBJECTS) $(DEVICES) Makefile.dev
	ar $(ARFLAGS) ../lib/libdev.a $(OBJECTS)

.c.o:
	$(CC) $(CFLAGS) $(LCFLAGS) $<

XIF:
	cd xif; make -f Makefile.xif; cd ..;

META:
	cd meta; make -f Makefile.meta; cd ..;

clean:
	rm $(OBJECTS)
	cd xif;  make -f Makefile.xif  clean; cd ..;
	cd meta; make -f Makefile.meta clean; cd ..;

