##############################################################################
#																			 #
#	Makefile for all modules of ug version 3								 #
#																			 #
#	created 16 December 1994												 #
#																			 #
##############################################################################


# include configuration and all makefile macro definitions
include ../ug.conf


# select your devices: one of { NIF, XIF, SIF, RIF }. META and PS are optional
DEVICES = $(IF)IF META PS
OBJECTS = devices.o sockcomm.o


# local C compiler flags
LCFLAGS = -I../include

all : $(OBJECTS) $(DEVICES) Makefile.dev
	$(ARCH_AR)  $(ARCH_ARFLAGS) ../lib/libdev$(IF).a $(OBJECTS) 

.c.o:
	$(ARCH_CC) $(UG_CFLAGS) $(LCFLAGS) $<

NIF:
	cd nif; make -f Makefile.nif; cd ..;

XIF:
	cd xif; make -f Makefile.xif; cd ..;

SIF:
	cd sif; make -f Makefile.sif; cd ..;

RIF:
	cd rif; make -f Makefile.rif; cd ..;

META:
	cd meta; make -f Makefile.meta; cd ..;

PS:
	cd ps; make -f Makefile.ps; cd ..;

XLIB: 
	rm -f ../lib/libdev.a
	$(ARCH_AR) $(ARCH_ARFLAGS) ../lib/libdevX.a $(OBJECTS)
	cd meta; make -f Makefile.meta; cd ..;
	cd xif; make -f Makefile.xif; cd ..;
	cd ps; make -f Makefile.ps; cd ..;

SLIB: 
	rm -f ../lib/libdev.a
	$(ARCH_AR) $(ARCH_ARFLAGS) ../lib/libdevS.a $(OBJECTS)
	cd meta; make -f Makefile.meta; cd ..;
	cd sif; make -f Makefile.sif; cd ..;
	cd ps; make -f Makefile.ps; cd ..;

RLIB: 
	rm -f ../lib/libdev.a
	$(ARCH_AR) $(ARCH_ARFLAGS) ../lib/libdevR.a $(OBJECTS)
	cd meta; make -f Makefile.meta; cd ..;
	cd rif; make -f Makefile.rif; cd ..;
	cd ps; make -f Makefile.ps; cd ..;

clean:
	rm -f *.o
	cd xif;  make -f Makefile.xif  clean; cd ..;
	cd sif;  make -f Makefile.sif  clean; cd ..;
	cd rif;  make -f Makefile.rif  clean; cd ..;
	cd meta; make -f Makefile.meta clean; cd ..;
	cd ps;   make -f Makefile.ps   clean; cd ..;

#preliminary: only xif+meta+ps (should be configurable in another way)
extract:
	$(ARCH_AR) $(ARCH_EXFLAGS) ../lib/libdev$(IF).a $(OBJECTS)
	cd xif;  make -f Makefile.xif  extract; cd ..;
	cd meta; make -f Makefile.meta extract; cd ..;
	cd ps;   make -f Makefile.ps   extract; cd ..;

xmc: extract all
	cd xif;  make -f Makefile.xif  clean; cd ..;
	cd meta; make -f Makefile.meta clean; cd ..;
	cd ps;   make -f Makefile.ps   clean; cd ..;
