objects = bitarray.o array.o table.o hashtabl.o
# lib = gen
# zip = $(src) evalfunc.hh array.hh hashtabl.hh template.hh symbolta.hh \
#        sp_ar_2d.hh bitarray.hh spbita2d.hh table.hh myadt.h
#
#
include ../makefile.inc
#
