##############################################################################
#																			 #
#	Makefile for parallel ug version										 #
#																			 #
#	created 17 August 1992													 #
#																			 #
##############################################################################



# include configuration and all makefile macro definitions
include ../../ug.conf

OBJECTS = xmain.o xshell.o xgraph.o

# local C compiler flags
LCFLAGS = -I../../include

all : $(OBJECTS) $(GUI) Makefile.xif
	$(ARCH_AR)  $(ARCH_ARFLAGS) ../../lib/libdevX.a $(OBJECTS) 

.c.o:
	$(ARCH_CC) $(UG_CFLAGS) $(LCFLAGS) $<

ON:
	echo "creating gui toolbox"
	cd gui; make -f Makefile.gui; cd ..;

OFF:
	echo "no gui toolbox"

clean:
	find . -name '*.o' -exec rm {} \; -print
	find . -name '*.a' -exec rm {} \; -print

extract:
	$(ARCH_AR) $(ARCH_EXFLAGS) ../../lib/libdevX.a $(OBJECTS)

xmc: extract all clean
