objects = adfront3.o adfront2.o meshing3.o meshing2.o netrule3.o netrule2.o \
	  parser3.o parser2.o ruler3.o ruler2.o findip.o \
          global.o meshtype.o nginterface.o improve3.o


include ../makefile.inc

