##############################################################################
#																			 #
#	Makefile for parallel ug version										 #
#																			 #
#	created 23 September 1997												 #
#																			 #
##############################################################################

.SUFFIXES : .c .m

# include configuration and all makefile macro definitions
include ../../ug.conf

OBJECTS = NeXTInterface.o UGShellWindow.o UGGraphWindow.o

# local C compiler flags
LCFLAGS = -I../../include -no-precomp -D_NEXT_SOURCE

all : $(OBJECTS) Makefile.nif
	$(ARCH_AR)  $(ARCH_ARFLAGS) ../../lib/libdevN.a $(OBJECTS) 

.c.o :
	$(ARCH_CC) $(UG_CFLAGS) $(LCFLAGS) $<

.m.o :
	$(ARCH_CC) $(UG_CFLAGS) $(LCFLAGS) $<

clean :
	rm -f *.o ../../lib/libdevN.a

extract :
	$(ARCH_AR) $(ARCH_EXFLAGS) ../../lib/libdevN.a $(OBJECTS)

xmc : extract all clean
