##############################################################################
#																			 #
#	Makefile for parallel ug version										 #
#																			 #
#	created 17 August 1992													 #
#																			 #
##############################################################################


# include configuration and all makefile macro definitions
include ../../ug.conf

OBJECTS = postscript.o

# local C compiler flags
LCFLAGS = -I../../include

all : $(OBJECTS) Makefile.ps
	$(ARCH_AR)  $(ARCH_ARFLAGS) ../../lib/libdev$(IF).a $(OBJECTS) 

.c.o:
	$(ARCH_CC) $(UG_CFLAGS) $(LCFLAGS) $<

clean:
	rm -f *.o

extract:
	$(ARCH_AR) $(ARCH_EXFLAGS) ../../lib/libdev$(IF).a $(OBJECTS)

xmc: extract all clean


