##############################################################################
#																			 #
#	Makefile for all modules of ug version 3								 #
#																			 #
#	created 16 December 1994												 #
#																			 #
##############################################################################

# include configuration and all makefile macro definitions
include ../ug.conf

OBJECTS = uginterface.o initui.o cmdint.o cmdline.o \
		  commands.o helpmsg.o avs.o tecplot.o teti.o

$(UG_LIB) : $(OBJECTS) Makefile.ui
	$(ARCH_AR) $(ARCH_ARFLAGS) $(UG_LIB) $(OBJECTS) 

ar : 
	$(ARCH_AR) $(ARCH_ARFLAGS) $(UG_LIB) $(OBJECTS) 

.c.o:
	$(ARCH_CC) $(UG_CFLAGS) $(NETGEN_CFLAGS) $<

clean:
	rm -f *.o

extract:
	$(ARCH_AR) $(ARCH_EXFLAGS) ../lib/libug$(UG_LIBSUFFIX).a $(OBJECTS)

xmc: extract $(UG_LIB) clean
