##############################################################################
#																			 #
#	Makefile for all modules of ug version 3								 #
#																			 #
#	created 16 December 1994												 #
#																			 #
##############################################################################


# include configuration and all makefile macro definitions
include ../ug.conf

OBJECTS = avs.o uginterface.o initui.o cmdint.o cmdline.o commands.o helpmsg.o tecplot.o

# local C compiler flags
LCFLAGS = -I../include

all: $(OBJECTS) Makefile.ui
	$(ARCH_AR) $(ARCH_ARFLAGS) ../lib/libug$(UG_LIBSUFFIX).a $(OBJECTS) 

.c.o:
	$(ARCH_CC) $(UG_CFLAGS) $(LCFLAGS) $<

clean:
	rm -f $(OBJECTS)


