##############################################################################
#																			 #
#	Makefile for all modules of ug version 3								 #
#																			 #
#	created 16 December 1994												 #
#																			 #
##############################################################################

# load architecture dependent makefile	
include ../ug.arch

# architecture-dependent makefile entries
include ../machines/mk.$(ARCHDIR)

# load configuration switches
include ../ug.conf

# local C compiler flags
LCFLAGS = -I../low -I../dddif -I../dev -I../dom -I../gm -I../numerics \
          -I../graph -I../gg -I../gg3d

# object files for both dimensions
OBJECTS = uginterface.o initui.o cmdint.o cmdline.o commands.o helpmsg.o

# objects for 2D version
OBJECTS2 =

# objects for 3D version
OBJECTS3 =

# main rules
2Dversion : $(OBJECTS) $(OBJECTS2) Makefile.ui
	ar $(ARFLAGS) ../lib/libug$(LIBSUFFIX).a $(OBJECTS) 

3Dversion : $(OBJECTS) $(OBJECTS3) Makefile.ui
	ar $(ARFLAGS) ../lib/libug$(LIBSUFFIX).a $(OBJECTS) 

# default rule
.c.o:
	$(CC) $(UGDEFINES) $(GRAPEDEFINE) $(CFLAGS) $(LCFLAGS) $<

# clean up
clean:
	rm $(OBJECTS)

