objects = vector.o sparsmat.o densemat.o basemat.o 
# vector.cc sparsmat.cc densemat.cc \
# iterativ.cc supervec.cc supermat.cc calccond.cc specmat.cc
#
# CCFL    += -pg
#
include ../makefile.inc
#
#

